name: CI/CD to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/lahmamiahm23/spring-boot-k8s-deployment:latest .
          docker tag ghcr.io/lahmamiahm23/spring-boot-k8s-deployment:latest ghcr.io/lahmamiahm23/spring-boot-k8s-deployment:${{ github.sha }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: lahmamiahm23
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/lahmamiahm23/spring-boot-k8s-deployment:latest
          docker push ghcr.io/lahmamiahm23/spring-boot-k8s-deployment:${{ github.sha }}

